### ISSUE TITLE
Missing fields to translate

### ISSUE THREAD

**Issue by MrBooze** [marcusatbang/charactersheets-translator#10]
Some things can not be translated, because there is no option for it! f.e. 3.5 monk: abundant step:
there is only the option to translate the non capital version: "Abundant step" the capital version: "ABUNDANT STEP" is nowhere to be found.

**Comment by marcus-downing** [comment]
I think this may be related to issue #3 . The "master" entries need updating.

**Comment by marcus-downing** [comment]
Can you check these now? They should be resolved with the new master list.

**Comment by MrBooze** [comment]
It's strange.When I search for "abundant" with the filter Games - All Games, it just finds "Abundant step" and it shows that it's just linked to the pathfinder entries and not the 3.5. monk.
And if I filter Games - D&D 3.5 it shows "ABUNDANT STEP".

So it seems to me, that there are 2 issues:
1. Missing link from "Abundant step" to the 3.5-Monk sheet
2. And the filter options seem to not work right

**Comment by marcus-downing** [comment]
Aha! I overlooked the fact that MySQL's `GROUP BY` is case insensitive, so it couldn't tell the difference between these three:

```
 ABUNDANT STEP
 Abundant Step
 Abundant step
```
