### ISSUE TITLE
Disambiguate "light" and "light"

### ISSUE THREAD

**Issue by marcus-downing** [marcusatbang/charactersheets-translator#7]
mrbooze:

> The term "light" has two different words in German: "Licht" (as emitted by the sun) and "leicht" (as the opposite of heavy). The translation entry is linked to both, so it is impossible to translate this correct.
> It occurs in `Pathfinder/GM/Kingdom/Kingdom` (as "leicht") and in `3.5/Extended/Artificer` & `3.5/Extended/Warmage` (as the spell "Licht"). Would it be possible to split this entry into two?

**Comment by MrBooze** [comment]
I fear I've found a second ambiguity: In german we use two words for "level" for two different things: For class-level, character-level, caster-level and most other thing it's "Stufe" for spell-level it's "Grad". So far it mostly turns out ok, because it's not so many times a stand alone word but on the spell book sheets, f.e.: http://translate.charactersheets.minotaur.cc/pdf/languages/german/dnd35/Core/Spell%20Book.pdf there it should read "Grad"

**Comment by marcus-downing** [comment]
That one might be easier to fix. I can just change the Spell Book to say "Spell Level".

**Comment by MrBooze** [comment]
yeah, that would be ok!

**Comment by marcus-downing** [comment]
Done.

**Comment by marcus-downing** [comment]
Ahem. A little too eager there.

**Comment by marcus-downing** [comment]
I think I have a plan for this. In future the entry will read "Light &lt;illumination&gt;" or "Light &lt;weight&gt;" depending on the page; and the translation script will pick the right translation by the same rules.

It can also be applied to other ambiguous entries _if_ they're clearly separated by page. If both versions of a word appear on the same page, I don't have an answer to it.

**Comment by MrBooze** [comment]
So let's hope that never happens! But I think the chances that this problem should show up are rather slim.

**Comment by marcus-downing** [comment]
This should be fixed just as soon as I can fix #3

**Comment by marcus-downing** [comment]
These new entries should be in the translator now.

**Comment by MrBooze** [comment]
There are now 3 options for light, where there should only be 2.
Light
Light <weight>
Light <illumination>

The first one still has 2 different translations.
